import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  main: {
    flex: 1,
  },
  input: {
    borderColor: "rgba(255,255,255,0.3)",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    color: "white",
    paddingVertical: 1,
    Width: 300,
  },
  search: {
    width: "50%",
    height: "50%",
    resizeMode: "stretch",
    alignSelf: "center",
    alignContent: "center",
    top: "30%",
    left: "10%",
  },
  textplaceholder: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    paddingHorizontal: 10,
  },
  main: {
    flex: 1,
    paddingHorizontal: 6,
    borderRadius: 0.2,
  },
  bgImage: {
    borderRadius: 2,
    width: "100%",
    height: 240,
    overflow: "hidden",
    resizeMode: "cover",
  },
  rateContainer: {
    backgroundColor: "#f2b917",
    width: 30,
    height: 20,
    marginBottom: 10,
    justifyContent: "flex-start",
    alignItems: "center",
    alignSelf: "baseline",
    placeItem: "baseline",
    top: 210,
    marginLeft: 10,
    borderRadius: 5,
  },
});
